(data_only_dirs
 goblint.2026-02-12_16-35-44.files
 mopsa.2026-02-10_20-41-53.files)

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/AdditionIntMin.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/AdditionIntMin.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint})))
   (diff? AdditionIntMin.yml.comparison.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/20051113-1.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/20051113-1.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint})))
   (diff? 20051113-1.yml.comparison.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/a.08.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/a.08.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint})))
   (diff? a.08.yml.comparison.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/NoConversion.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/NoConversion.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint})))
   (diff? NoConversion.yml.comparison.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/bresenham-ll_valuebound1.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/bresenham-ll_valuebound1.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint})))
   (diff? bresenham-ll_valuebound1.yml.comparison.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/uname-1.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/uname-1.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint}))) ; includes also Mopsa's patched file
   (diff? uname-1.yml.comparison.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-10_20-41-53.files/SV-COMP26_no-overflow/uname-1.yml/checks.json)
  (:goblint goblint.2026-02-12_16-35-44.files/SV-COMP26_no-overflow/uname-1.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/busybox-1.22.0/uname-1.i %{mopsa} %{goblint}))) ; doesn't include Mopsa's patched file
   (diff? uname-1.yml.comparison-2.json comparison.json))))

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (glob_files *.comparison.json))
 (action
  (progn
   (with-stdout-to tmp.json
    (run ovd summarize *.comparison.json))
   (diff? summary.json tmp.json))))
