(library
 (name dashboard)
 (wrapped true)
 (modules
  conflict
  proofObligation
  compareProofObligations
  report
  project
  utils)
 (private_modules utils)
 (preprocess
  (pps ppx_deriving.std ppx_deriving_hash ppx_yojson_conv))
 (libraries
  ppx_deriving
  ppx_deriving_hash
  ppx_yojson_conv
  yojson
  sha
  fileutils))
