/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
#include "stdlib.h"
int overflow_anoted(void)
{
  int __retres;
  int test[50];
  {
    int i = 0;
    while ((unsigned long)i < sizeof(test) / sizeof(int)) {
      test[i] = i;
      i ++;
    }
  }
  __retres = 0;
  return __retres;
}


