(data_only_dirs
 goblint.2026-02-12_14-33-25.files
 mopsa.2026-02-12_14-51-30.files)

(rule
 (alias runtest)
 (deps
  (sandbox always)
  (:mopsa mopsa.2026-02-12_14-51-30.files/SV-COMP26_no-overflow/uniq_3args_ok.yml/checks.json)
  (:goblint goblint.2026-02-12_14-33-25.files/SV-COMP26_no-overflow/uniq_3args_ok.yml/checks.json))
 (action
  (progn
   (with-stdout-to comparison.json
    (ignore-stderr
     (run ovd compare --format json --filter-category "Signed integer overflow in arithmetic operator" --filter-category "Unsigned integer overflow in arithmetic operator" --filter-path /home/holterka/sv-benchmarks/c/** %{mopsa} %{goblint})))
   (diff? uniq_3args_ok.yml.comparison.json comparison.json))))
